### ISSUE TITLE
Update Default Output Style/Carto and include Settings

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-erg-widget#23]
Currently, this is the output generated from the ERG widget:
![image](https://user-images.githubusercontent.com/13024357/31200873-5e8d4800-a911-11e7-87ff-cad942ff87b4.png)

I can see 3 distinct areas
1. The immediate spill circle right around the input point. This should have the most intense color, probably red with ~25% transparency
2. the fan that takes into account the wind direction and other parameters based on the chemical/placard type. This seems like the next most important area. It is currently a think black dashed line, and a thin black solid line. I think that these outlines should also be red, although a lighter shade than the immediate spill circle. This area should also should have a fill, maybe at ~60% transparency. 
3. The third area is the bounding box that touches the vertices of the fan and the initial spill point. This outline could be either thin or a less intense color than red, and it doesn't need a fill, maybe one that is almost completely transparent, at ~90%. 

This is a nice example; the areas are represented with varying transparency, but the output graphic is still uniform and it doesn't block out basemap elements: 
![image](https://user-images.githubusercontent.com/13024357/31201109-544c029a-a912-11e7-85f5-db19becf69d5.png)

**Comment by joebayles** [comment]
Verified.
