### ISSUE TITLE
Add hydrology feature service to configuration settings

### ISSUE THREAD

**Issue by llsjr2** [Esri/solutions-erg-widget#28]
Adding a hydrology feature service option to the configuration page would enhance the usability of widget.  It provide information that is critical to environmental impacts of the hazard.  Also, provides information on water around the site that could affect certain chemicals that react with water to increase the danger.

![water_reactive_chemicals](https://user-images.githubusercontent.com/30242778/31361448-3ce72d60-ad08-11e7-95e8-899fff306e2d.PNG)

**Comment by adgiles** [comment]
When selecting a material if the name is followed by “(when spilled in water)”:

![capture](https://user-images.githubusercontent.com/3740334/35738395-b16b71b8-0826-11e8-8125-268c8e32ff4a.PNG)

This means that the chemical relates to Table 2 and the user is informed of what other chemicals they might want to consider for the material type:

For instance if you select '1745 | Bromine pentafluoride (when spilled in water)', this will be the warning message:

![capture](https://user-images.githubusercontent.com/3740334/35738612-458d974a-0827-11e8-856b-25835ce70dba.PNG)

relating to this part of table 2:

![capture](https://user-images.githubusercontent.com/3740334/35738655-63b2c60a-0827-11e8-980b-cb6fdc0369b9.PNG)

**Comment by llsjr2** [comment]
The solution that @adgiles did completes the intent to ensuree that the chemicals that react to water are identified.  The add of the page for the reaction displays the critical information required to perform the cleanup and other activies.  Recommend closing.
