### ISSUE TITLE
Release ERG widget

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-erg-widget#39]
### *After* documentation, code, testing is complete
- [x] final version of solution placed on and zipped up from our ReleaseStaging folder location. This includes folders for the Widget, and a Resources folder for our final offline documentation @Dbarnes1 
- [x] pre-release testing of online documentation on solutions staging 
- [x] prepare a new download and location for esri downloads @Dbarnes1 
- [x] add zipped solution as an item to our deployment organization with proper tags for solutions deployment tool and proper thumbnail and link for the solutions gallery, don't share yet. Share the day of release
- [x] GitHub release erg widget @joebayles

**Comment by Dbarnes1** [comment]
This is basically done, just need to test the doc and share out our gallery item once we get close to release date. Links on slack

**Comment by Dbarnes1** [comment]
can we put a wait tag on here or something?

**Comment by joebayles** [comment]
@Esri/arcgis-defense-solutions looks like this needs a gallery item.

**Comment by Dbarnes1** [comment]
I thought I had created a gallery item already, but simply left it unshared. Now I'm struggling to access the folder view of the gallery items on our deployment org.

**Comment by Dbarnes1** [comment]
found it. gallery item is up.
