### ISSUE TITLE
Documentation - Overview Page Wording

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-erg-widget#42]
The last bullet point in the overview description needs changing to reflect that the demographic and facilities data are no longer within the widget:

![untitled](https://user-images.githubusercontent.com/3740334/31652371-c57ce2dc-b316-11e7-90e0-24e4c88f21fa.png)

I suggest it should be changed to:

> Publish the graphic to ArcGIS Enterprise/Portal for ArcGIS for dissemination.

**Comment by adgiles** [comment]
The wording on this still looks the same reopening:

![untitled](https://user-images.githubusercontent.com/3740334/31763569-80554dda-b473-11e7-9d17-16d37fc94fcd.png)

**Comment by joebayles** [comment]
Verified. Closing.
