### ISSUE TITLE
Documentation - Install the ERG Widget

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-erg-widget#48]
Point 1 on the install the ERG widget is worded incorrectly it current says:

> Download the Emergency Reference Guide

it should say:

> Download the Emergency Response Guide

![untitled](https://user-images.githubusercontent.com/3740334/31654205-20b417b6-b2da-11e7-8646-77e98a7987b5.png)

**Comment by joebayles** [comment]
Verified.
