### ISSUE TITLE
Documentation - Install the ERG Widget

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-erg-widget#49]
Point 3 on the install the ERG widget is worded incorrectly it current says:

> Use your extraction utility to extract EmergencyReferenceGuide.zip to a folder on your computer..

it should say:

> Use your extraction utility to extract EmergencyResponseGuide.zip to a folder on your computer..

![untitled](https://user-images.githubusercontent.com/3740334/31654278-6292d596-b2da-11e7-8443-64a6e8ff66bb.png)

**Comment by joebayles** [comment]
Verified.
