### ISSUE TITLE
Documentation - Configuring the ERG widget

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-erg-widget#50]
Point 3 within the configuring the ERG widget is not representative of the settings in the widget, there are no longer symbology and layer tabs and the symbology settings do not match what is implemented (Fire zone is missing):

![untitled](https://user-images.githubusercontent.com/3740334/31654951-584d5172-b2dc-11e7-9579-3571b0bea435.png)

![untitled](https://user-images.githubusercontent.com/3740334/31655260-2f9fadbe-b2dd-11e7-939a-4f41960f8bb7.png)

**Comment by joebayles** [comment]
Verified.
