### ISSUE TITLE
Documentation - Resources - Release Notes

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-erg-widget#56]
Same as issue #42 the wording is now incorrect on the following:

> Assess spill impact with demographic and facilities data, and publish the graphic to ArcGIS Enterprise/Portal for ArcGIS for dissemination.

Change to:

> Publish the graphic to ArcGIS Enterprise/Portal for ArcGIS for dissemination.

![untitled](https://user-images.githubusercontent.com/3740334/31656267-f3b25006-b2df-11e7-8d7f-2401ef6c6a17.png)

**Comment by joebayles** [comment]
Verified.
