### ISSUE TITLE
Documentation - Install the ERG Widget - ArcGIS Enterprise 10.5.1

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-erg-widget#59]
The documentation for installing the widget should also document the workflow of installing the widget in Enterprise 10.5.1 as explained in this blog:

https://blogs.esri.com/esri/arcgis/2017/06/30/web-appbuilder-for-arcgis-now-supports-custom-widgets-in-arcgis-enterprise-10-5-1/

This workflow also needs testing

**Comment by Dbarnes1** [comment]
The reason I'm dragging on this is because our dev portal, the National Security portal on AWS, is still at 10.5. Ideally, I'd like to test the workflow there once it upgrades to 10.5.1, I'll touch base with others on getting this upgraded.

**Comment by adgiles** [comment]
As the widget is now going to be part of Core Web AppBuilder, I no longer think this issue is valid and can be closed

**Comment by lfunkhouser** [comment]
This issue is invalid now. Closing.
