### ISSUE TITLE
Pre-Release Holistic Test

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-erg-widget#64]
Putting an issue out here so someone can go through the widget, starting from the download item, just to see if there are any showstoppers with the download or the widget itself. This will go out for the December release. I'm thinking a quick check and running through the workflow doc as you use the widget. Its basically brand new from the previous version.

Here is the link to the new download item: http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.main&downloadid=2083

@BobBooth @ACueva I'd appreciate it if either of you guys could look at it quickly, it could use a fresh set of eyes before we completely wrap up this dev effort. 

@joebayles @adgiles FYI

**Comment by Dbarnes1** [comment]
I'm going to pause this for now, there are a couple more changes being pushed in before we release

**Comment by ACueva** [comment]
@Dbarnes1 Let us know when we're good to test again.

**Comment by lfunkhouser** [comment]
Closing. ERG was tested and released in December 2017.
