### ISSUE TITLE
Sample app errors

### ISSUE THREAD

**Issue by canadajebus** [Esri/solutions-erg-widget#65]
### Bug or Enhancement

Splash screen link to "Learn more info about...", Page Not Found:
http://solutions.arcgis.com/defense/help/emergency-response-guide/

Widget fails to load, 404 on resource:
https://nationalsecurity.esri.com/solutionsweb/EmergencyResponseGuide/widgets/ERG/templates/EditOutputCoordinate.html?wab_dv=2.6

### Repo Steps or Enhancement details

Loaded sample app in IE/Crome:
https://nationalsecurity.esri.com/solutionsweb/EmergencyResponseGuide/

### Screenshots

Nil

**Comment by adgiles** [comment]
Hi Joseph @canadajebus,

Thanks for your issue, the first link:

http://solutions.arcgis.com/defense/help/emergency-response-guide/

Will not become available until the next update of the solutions pages, due December time.

I am not seeing the 404 issue on your second link, which browser are you using?

Regards

Anthony

**Comment by canadajebus** [comment]
Ok, makes sense for the first one.  

I am getting that 2nd 404 in IE, Firefox, and Chrome.

I remember it was working last week at the TEM when you guys showed this.  Should I wait for a release announcement before showing this to Esri Canada clients?


Should I hold off on showing this to our Esri Canada clients?

**Comment by adgiles** [comment]
I just checked the server and the .html page is definitely there, can you try a hard refresh of your browser and see if it sorts its self out. Best way to do this is in Chrome, load the page press F12 and then right click the refresh button:

![untitled](https://user-images.githubusercontent.com/3740334/32171001-d17ddb10-bd6e-11e7-9cbd-dc7957e70e42.png)

Then select empty cache and hard reload

**Comment by canadajebus** [comment]
Yes that worked, thank you.
