### ISSUE TITLE
The Show Fire Isolation Zone toggle options are reversed

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-erg-widget#67]
Issue reported by @MikeTschudi 

### Bug or Enhancement
The Show Fire Isolation Zone toggle position for "on" and "off" are reversed in the UI.

### Repo Steps or Enhancement details
The user slides the toggle right (red) to turn it off and slides it left (green) to turn it on, as shown in the following screenshots: 

### Screenshots
![image](https://user-images.githubusercontent.com/3800729/35173834-c4e67edc-fd21-11e7-9cce-175531770856.png) 
![image](https://user-images.githubusercontent.com/3800729/35173844-cd3aec8a-fd21-11e7-9ab7-5ca5aede819d.png)

The standard for iOS-style toggles is slide right to get it on/green and left to get it off/red.
![image](https://user-images.githubusercontent.com/3800729/35173998-8a4f2e6c-fd22-11e7-9edb-b9ee86236a54.png)
 

Version found:
ERG December 2017
WAB 2.6

**Comment by adgiles** [comment]
If we decide we do want to change this it is a very easy fix. In the style.css file change the following lines:

239: background: #e04f1d; to background: #adadad;
257: right : 2px; to right: 14px;
282: right : 14px; to right: 2px;

This will give the following:

Off:
![capture](https://user-images.githubusercontent.com/3740334/35507319-3ad97a26-04e4-11e8-997a-515fbfc7daf1.PNG)
On:
![capture1](https://user-images.githubusercontent.com/3740334/35507326-3ee7c460-04e4-11e8-8668-c5f9a460fec7.PNG)

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-erg-widget/pull/71

**Comment by topowright** [comment]
verified and ready to close
