### ISSUE TITLE
Emergency Response Guide widget folder should be renamed

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-erg-widget#68]
### Bug or Enhancement

The folder that you use to drop in the WAB ...\client\stemapp\widgets folder is named "ERG", this is a different naming convention than the widgets that come with WAB, suggest changing the name of the folder to "EmergencyResponseGuide"

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-erg-widget/pull/70

**Comment by topowright** [comment]
This has been done and has been pushed to devtopia.

**Comment by lfunkhouser** [comment]
The folder is listed as ERG in the Contents of the Resources documentation in CMS. Adding CMS documentation label and moving back to the Backlog.

**Comment by topowright** [comment]
This can be closed based on the push of the documentation that has been updated in WAB. The ERG spells out the name of the solution. We also no longer walk the user thru the adding of the widget to WAB being that it is already there.
