### ISSUE TITLE
Removing unnecessary files

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-erg-widget#74]
![image](https://user-images.githubusercontent.com/5488313/35935436-59b4046c-0bf5-11e8-8afa-ea5176863ca4.png)

@adgiles, @lfunkhouser 

This is the first bit of feedback from the Dev team

**Comment by adgiles** [comment]
@topowright The PDF’s are the pages of the ERG guide we want to link to, if we remove them that functionality will not be available.

I don’t know what the second point is referring to

**Comment by llsjr2** [comment]
@topowright   Agree with @adgiles     The pdf files were created to provide the functionality to add the ERG book into the widget and make them readily available.      It was a function that was particularly designed.
 https://github.com/Esri/solutions-erg-widget/issues/34

**Comment by adgiles** [comment]
I have checked through the images folder and found five images that were not being used. This have been removed in PR https://github.com/Esri/solutions-erg-widget/pull/75

I don't agree with the first comment that the widgets do not include png files, every core widget contains an images folder and is documented here:

https://developers.arcgis.com/web-appbuilder/guide/developer-s-guide-overview.htm

**Comment by topowright** [comment]
verified
