### ISSUE TITLE
Feedback from Dev Group

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-erg-widget#76]
![image](https://user-images.githubusercontent.com/5488313/35976926-753bb044-0c96-11e8-90a6-cd63eae79652.png)

Response from @adgiles: Done

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35976956-8d208c3e-0c96-11e8-8fba-d1047e0305fe.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977318-a40f59f6-0c97-11e8-9e61-038ed91ce5c2.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977336-b5784770-0c97-11e8-886e-39abd05c226d.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977357-c7a5a104-0c97-11e8-8a8e-95f40b0e585e.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977379-d90d9172-0c97-11e8-9d47-0f8489e8a4e3.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977404-e9ffb9e2-0c97-11e8-8296-60bce6ebd08c.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977441-01d2af8e-0c98-11e8-8679-0565b375302c.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977490-15f0ab74-0c98-11e8-98d1-68e41b817a8c.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977508-22520f0c-0c98-11e8-9c5c-91ec9e8ebabc.png)

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/35977524-32138d44-0c98-11e8-8b72-1874abd95f0b.png)

**Comment by adgiles** [comment]
Comment made in each issue above.

Changes made in this PR https://github.com/Esri/solutions-erg-widget/pull/77

**Comment by topowright** [comment]
verified

**Comment by lfunkhouser** [comment]
@topowright update the Enterprise PR with the comments from @adgiles before closing this issue.
