### ISSUE TITLE
Publishing ERG with incorrect credentials

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-erg-widget#79]
Issues were identified with the GRG widget with errors not being caught and processed within the publishing workflow:

https://github.com/Esri/solutions-grg-widget/issues/172
https://github.com/Esri/solutions-grg-widget/issues/173

The same fixes that addressed these issues need to be made to the ERG widget

**Comment by adgiles** [comment]
Addressed in PR: https://github.com/Esri/solutions-erg-widget/pull/80

Check list tests need updating to test different accounts:

- Valid accounts that are not part of the org
- Valid accounts that are in the org but are only viewers

**Comment by topowright** [comment]
@adgiles @dfoll @kgonzago if I understand this correctly only a user of the same Portal/Online org will be able to use the widget to publish content. To go further to make sure I am being clear the person who registers the app must only share with other users who are apart of that same org/portal. If that is the case then I am getting the correct feedback in the widget


@adgiles can we make the text populate to like this: 
You are currently signed in as: 'wright9739'. 
You do not have access to this resource: https://arcgisfordefense.maps.arcgis.com/sharing/rest/portals/selfERG- Publishing Issueswith Web AppBuilder for ArcGIS

I would like to see the first two lines without having to shift the widget to see the text: 
![image](https://user-images.githubusercontent.com/5488313/36238511-dfd221ba-11b7-11e8-8d7c-8a3294b50e94.png)

**Comment by topowright** [comment]
The logic is correct I am requesting that we just shift the text in the dialog

**Comment by adgiles** [comment]
@topowright Correct you must be a member of the portal/org that the application is being hosted on to publish content.

I have addressed the issue of having to scroll to see the whole line in PR #82. But the only way i could do it was to wrap the line mid URL as there are not spaces to make a clean break.

It is unlikely that the user will get to see this message due to the new publishing workflow addressed in issue #81

**Comment by topowright** [comment]
This has been addressed and pushed to Devtopia
