### ISSUE TITLE
Typo on configuration window

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-erg-widget#84]
### Bug or Enhancement
On the configure page there is a setting for the "Down Wind Zone" but it should read "Downwind Zone".  Not sure if the settings when you are using the app access this page, or there another group of settings that get applied, but this also appears by clicking the settings button when you are using the app. 

### Screenshots
![image](https://user-images.githubusercontent.com/5322669/36618999-0fc183ac-18a2-11e8-9af2-7403d259bb4b.png)
![image](https://user-images.githubusercontent.com/5322669/36619021-269d0f4c-18a2-11e8-8abb-83830c08438a.png)

**Comment by dfoll** [comment]
@lfunkhouser is this something we want to try to have fixed for this release of Web AppBuilder, or let it go until next release?

**Comment by dfoll** [comment]
@adgiles

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-erg-widget/pull/85

**Comment by dfoll** [comment]
PR in devtopia for this https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11925
