### ISSUE TITLE
Release-ready ERG

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-erg-widget#87]
WAB Dev team provided feedback on the widget. 
[ERG.zip](https://github.com/Esri/solutions-erg-widget/files/1760188/ERG.zip)

Actions needed to complete this issue:
- [x] Review changes/suggestions from WAB team
- [x] Implement changes
- [x] Push changes to Devtopia
- [x] Test changes on DevEXT
- [x] Test from Developer Edition daily

FYI: @topowright @dfoll @ACueva

**Comment by adgiles** [comment]
UI Changes addressed, latest code in https://github.com/Esri/solutions-erg-widget/tree/ag/wab-dev

@kgonzago can you move up to devtopia ASAP as there has been some string changes

**Comment by kgonzago** [comment]
Pushed to Devtopia in this [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11956)

**Comment by dfoll** [comment]
@kgonzago @adgiles  do you want me to test this, or wait until they merge into devtopia?

**Comment by kgonzago** [comment]
@dfoll The [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11956) for ERG in Devtopia was merged last night. Not sure if it made it into this morning's build but may want to check if you intend to start testing.

**Comment by adgiles** [comment]
@topowright @dfoll @ACueva 

UI changes are now showing in the daily build, good to start testing

**Comment by BobBooth** [comment]
Found an issue while testing where for some material types, the widget locks up, the tab goes unresponsive.
https://github.com/Esri/solutions-erg-widget/issues/89

**Comment by BobBooth** [comment]
Widget generally looking good. Comparing widget to UI suggestions, saw a minor discrepancy. Not sure worth fixing.
https://github.com/Esri/solutions-erg-widget/issues/90

**Comment by BobBooth** [comment]
Impeded by this issue
https://github.com/Esri/solutions-erg-widget/issues/89
some material types lock up the web app.
Probably related to incorrect values in the json file.

**Comment by dfoll** [comment]
this is still open because i have not seen #89 working dev edition daily snapshot but saw #89 working on DevExt
