### ISSUE TITLE
This repo will no longer be maintained

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-erg-widget#94]
The Emergency Response Guide widget is now offered through Web AppBuilder for ArcGIS. The code will be maintained there and issues managed through Enterprise GitHub.

- [x] Make sure there is a release prior to making changes.
- [x] remove code from this repo
- [x] mark repo as no longer maintained
- [x] update repo to direct users to Web AppBuilder for ArcGIS
- [x] direct customers to report issues through support rather than this repository

**Comment by dfoll** [comment]
can be moved to done after  #100 is merged

**Comment by lfunkhouser** [comment]
verified as fixed
